name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "14" # Asegúrate de usar una versión de Node.js que sea compatible con tu proyecto
      - run: npm ci
      - run: npm install -g @angular/cli
      - run: ng build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SGCP_28EA1 }}"
          channelId: live
          projectId: sgcp-28ea1
